### ISSUE TITLE
exporting all shaders in shadertoy?

### ISSUE THREAD

**Issue by smkplus** [KoltesDigital/shadertoy-exporter#3]
can you insert a option to downloading all shader in shadertoy

**Comment by KoltesDigital** [comment]
Hi,

Can you clarify your request: do you want to download the 100000+ shaders of ShaderToy?

**Comment by smkplus** [comment]
> Hi,
> 
> Can you clarify your request: do you want to download the 100000+ shaders of ShaderToy?

yeah I want to download all shaders.

**Comment by KoltesDigital** [comment]
That's out of scope of this tool.

ShaderToy provides no API to do so, therefore you can only rely on HTTP requests to crawl the site. Any modern language has functions to send HTTP requests, so feel free to pick yours.

Besides, pay attention to licenses. Shaders belong to their author, and may be released under a restrictive license. There's no unified way to know it, because it's all text comments in the shader.
